### ISSUE TITLE
Bug: Config Server label needs noted

### ISSUE THREAD

**Issue by sadukie** [microsoft/azure-spring-apps-training#151]
In [Configure a Spring Cloud Config Server - Configure Azure Spring Cloud to access the Git Repository](https://github.com/microsoft/azure-spring-cloud-training/blob/master/04-configure-a-spring-cloud-config-server/README.md#configure-azure-spring-cloud-to-access-the-git-repository), the **Label** field is not addressed.

Some things to note:

* The default value for **Label** is `master`.
* If your Git repo does not have a master branch - as most have moved on to the `main` branch as a default, the **Label** should be set to `main`.
* If you want the config server to look at a different branch or tag, that value should be used for **Label**.

**Comment by jdubois** [comment]
Yes I totally agree on this. In fact I just changed yesterday [our Microsoft Learn based on this workshop ](https://docs.microsoft.com/en-us/learn/modules/azure-spring-cloud-workshop/) to have exactly the same fix!
@selvasingh feel free to assign this to me if you want me to do this change.
