### ISSUE TITLE
Azure Spring Apps rebranding

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-spring-apps-training#156]
Hello Julien @jdubois ,
Could you please update the repo URL to [https://github.com/microsoft/azure-spring-apps-training](https://github.com/microsoft/azure-spring-apps-training) ? :)
Thank you,
Steve

**Comment by jdubois** [comment]
This is unfortunately not possible, as it would break all the incoming links to this repo, and destroy its SEO.

**Comment by jdubois** [comment]
After more discussion, the rebranding is done! Not sure what the impact on the SEO will be.
